version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:3.13
    volumes:
      - ..:/workspaces/haefele-connect-mesh:cached
    command: sleep infinity

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "0.0.0.0:1883:1883"
    volumes:
      - ../config/mosquitto:/mosquitto/config:ro
      - mosquitto-data:/mosquitto/data
      - ../config/mosquitto/log:/mosquitto/log

volumes:
  mosquitto-data:
