version: "3.8"
services:
  devcontainer:
    image: ghcr.io/qnimbus/haefele-connect-mesh/devcontainer:latest
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/haefele-connect-mesh:cached
      - pip-cache:/home/vscode/.cache/pip
      - pip-local:/home/vscode/.local/lib
      - pip-bin:/home/vscode/.local/bin
      - npm-cache:/home/vscode/.npm
    command: sleep infinity

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "0.0.0.0:1883:1883"
    volumes:
      - ../config/mosquitto:/mosquitto/config:ro
      - mosquitto-data:/mosquitto/data
      - ../config/mosquitto/log:/mosquitto/log

volumes:
  mosquitto-data:
  pip-cache:
  pip-local:
  pip-bin:
  npm-cache:
