name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"    # every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || github.ref == 'refs/heads/main'
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
